/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface ProofVerifierInterface extends utils.Interface {
  functions: {
    "PROVING_SYSTEM_ID()": FunctionFragment;
    "VERSION_HASH()": FunctionFragment;
    "verify(uint256,uint256,bytes32[],bytes32[],uint256,uint256)": FunctionFragment;
    "vkey()": FunctionFragment;
    "zkVerify()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "PROVING_SYSTEM_ID"
      | "VERSION_HASH"
      | "verify"
      | "vkey"
      | "zkVerify"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "PROVING_SYSTEM_ID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VERSION_HASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verify",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(functionFragment: "vkey", values?: undefined): string;
  encodeFunctionData(functionFragment: "zkVerify", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "PROVING_SYSTEM_ID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VERSION_HASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vkey", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "zkVerify", data: BytesLike): Result;

  events: {};
}

export interface ProofVerifier extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ProofVerifierInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    PROVING_SYSTEM_ID(overrides?: CallOverrides): Promise<[string]>;

    VERSION_HASH(overrides?: CallOverrides): Promise<[string]>;

    verify(
      domainId: PromiseOrValue<BigNumberish>,
      aggregationId: PromiseOrValue<BigNumberish>,
      publicInputs: PromiseOrValue<BytesLike>[],
      merklePath: PromiseOrValue<BytesLike>[],
      leafCount: PromiseOrValue<BigNumberish>,
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    vkey(overrides?: CallOverrides): Promise<[string]>;

    zkVerify(overrides?: CallOverrides): Promise<[string]>;
  };

  PROVING_SYSTEM_ID(overrides?: CallOverrides): Promise<string>;

  VERSION_HASH(overrides?: CallOverrides): Promise<string>;

  verify(
    domainId: PromiseOrValue<BigNumberish>,
    aggregationId: PromiseOrValue<BigNumberish>,
    publicInputs: PromiseOrValue<BytesLike>[],
    merklePath: PromiseOrValue<BytesLike>[],
    leafCount: PromiseOrValue<BigNumberish>,
    index: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  vkey(overrides?: CallOverrides): Promise<string>;

  zkVerify(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    PROVING_SYSTEM_ID(overrides?: CallOverrides): Promise<string>;

    VERSION_HASH(overrides?: CallOverrides): Promise<string>;

    verify(
      domainId: PromiseOrValue<BigNumberish>,
      aggregationId: PromiseOrValue<BigNumberish>,
      publicInputs: PromiseOrValue<BytesLike>[],
      merklePath: PromiseOrValue<BytesLike>[],
      leafCount: PromiseOrValue<BigNumberish>,
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    vkey(overrides?: CallOverrides): Promise<string>;

    zkVerify(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    PROVING_SYSTEM_ID(overrides?: CallOverrides): Promise<BigNumber>;

    VERSION_HASH(overrides?: CallOverrides): Promise<BigNumber>;

    verify(
      domainId: PromiseOrValue<BigNumberish>,
      aggregationId: PromiseOrValue<BigNumberish>,
      publicInputs: PromiseOrValue<BytesLike>[],
      merklePath: PromiseOrValue<BytesLike>[],
      leafCount: PromiseOrValue<BigNumberish>,
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    vkey(overrides?: CallOverrides): Promise<BigNumber>;

    zkVerify(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    PROVING_SYSTEM_ID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    VERSION_HASH(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    verify(
      domainId: PromiseOrValue<BigNumberish>,
      aggregationId: PromiseOrValue<BigNumberish>,
      publicInputs: PromiseOrValue<BytesLike>[],
      merklePath: PromiseOrValue<BytesLike>[],
      leafCount: PromiseOrValue<BigNumberish>,
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    vkey(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    zkVerify(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
