/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface IVerifyProofAggregationInterface extends utils.Interface {
  functions: {
    "verifyProofAggregation(uint256,uint256,bytes32,bytes32[],uint256,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "verifyProofAggregation"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "verifyProofAggregation",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "verifyProofAggregation",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IVerifyProofAggregation extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IVerifyProofAggregationInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    verifyProofAggregation(
      _domainId: PromiseOrValue<BigNumberish>,
      _aggregationId: PromiseOrValue<BigNumberish>,
      _leaf: PromiseOrValue<BytesLike>,
      _merklePath: PromiseOrValue<BytesLike>[],
      _leafCount: PromiseOrValue<BigNumberish>,
      _index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  verifyProofAggregation(
    _domainId: PromiseOrValue<BigNumberish>,
    _aggregationId: PromiseOrValue<BigNumberish>,
    _leaf: PromiseOrValue<BytesLike>,
    _merklePath: PromiseOrValue<BytesLike>[],
    _leafCount: PromiseOrValue<BigNumberish>,
    _index: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    verifyProofAggregation(
      _domainId: PromiseOrValue<BigNumberish>,
      _aggregationId: PromiseOrValue<BigNumberish>,
      _leaf: PromiseOrValue<BytesLike>,
      _merklePath: PromiseOrValue<BytesLike>[],
      _leafCount: PromiseOrValue<BigNumberish>,
      _index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    verifyProofAggregation(
      _domainId: PromiseOrValue<BigNumberish>,
      _aggregationId: PromiseOrValue<BigNumberish>,
      _leaf: PromiseOrValue<BytesLike>,
      _merklePath: PromiseOrValue<BytesLike>[],
      _leafCount: PromiseOrValue<BigNumberish>,
      _index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    verifyProofAggregation(
      _domainId: PromiseOrValue<BigNumberish>,
      _aggregationId: PromiseOrValue<BigNumberish>,
      _leaf: PromiseOrValue<BytesLike>,
      _merklePath: PromiseOrValue<BytesLike>[],
      _leafCount: PromiseOrValue<BigNumberish>,
      _index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
