/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IVerifyProofAggregation,
  IVerifyProofAggregationInterface,
} from "../../../contracts/interfaces/IVerifyProofAggregation";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_domainId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_aggregationId",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "_leaf",
        type: "bytes32",
      },
      {
        internalType: "bytes32[]",
        name: "_merklePath",
        type: "bytes32[]",
      },
      {
        internalType: "uint256",
        name: "_leafCount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_index",
        type: "uint256",
      },
    ],
    name: "verifyProofAggregation",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IVerifyProofAggregation__factory {
  static readonly abi = _abi;
  static createInterface(): IVerifyProofAggregationInterface {
    return new utils.Interface(_abi) as IVerifyProofAggregationInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IVerifyProofAggregation {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IVerifyProofAggregation;
  }
}
